pipeline{
  agent any
  tools{
    nodejs 'Node20'
  }
  environment {
    APP_NAME = "pems_fe"
    DEPLOYMENT_NAME = "pems-fe"
    DOCKER_USER = "theanh0906"
    DOCKER_PASS = "dockerhub-credentials"
    IMAGE_NAME = "${DOCKER_USER}/${APP_NAME}"
    IMAGE_TAG = "${IMAGE_TAG}"
    ARGO_CREDENTIALS="argocd-credentials"
    ARGO_TOKEN="argocd-token"
    IP_ARGO="192.168.126.130:32311"
    GIT_REPO = "https://github.com/theanhtr/PEMS.git"
    NAME_PROJECT_TEST_ARGO_RESTART="pems-test"
    //JENKINS_API_TOKEN = credentials('JENKINS_API_TOKEN')
  }
  stages{
    stage('Cleanup workspace'){
      steps{
        cleanWs()
      }
    }
    
    stage('Checkout'){
      steps{
        git branch: "${ENV_BUILD}", credentialsId: 'github-credentials', url: "${GIT_REPO}"
      }
    }

    stage("Build and push docker image"){
      steps{
        dir('FE') {
          script{
            docker.withRegistry('', DOCKER_PASS) {
              docker_image = docker.build("${IMAGE_NAME}", "--build-arg BUILD_ENV_ARG=${ENV_BUILD} .")
            }

            docker.withRegistry('', DOCKER_PASS) {
              docker_image.push("${IMAGE_TAG}")
            }

            sh "docker rmi ${IMAGE_NAME}:${IMAGE_TAG}"
          }
        }
      }
    }


    // stage("Trigger CD pipeline"){
    //   steps{
    //     script{
    //       sh "curl -v -k --user admin:${JENKINS_API_TOKEN} -X POST -H 'cache-control: no-cache' -H 'content-type: application/x-www-form-urlencoded' --data 'IMAGE_TAG=${IMAGE_TAG}' 'http://172.28.73.189:8080/job/discord_update_image_tag/buildWithParameters?token=discord-token'"
    //     }
    //   }
    // }

    stage("Restart Deployment"){
      steps{
        script{
          withCredentials([
            usernamePassword(credentialsId: "${ARGO_CREDENTIALS}", usernameVariable: 'USER', passwordVariable: 'PASSWORD'),
            string(credentialsId: "${ARGO_TOKEN}", variable: 'TOKEN'),
          ]) {
              sh """
                  argocd login ${IP_ARGO} --username ${USER} --password ${PASSWORD} --insecure --auth-token ${TOKEN}
                  argocd app actions run ${NAME_PROJECT_TEST_ARGO_RESTART} restart --kind Deployment --resource-name ${DEPLOYMENT_NAME} --auth-token ${TOKEN}
              """
          }
        }
      }
    }
  }
}