--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.225.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 10/30/2024 7:45:58 PM
-- Server version: 8.0.39
--

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

--
-- Set SQL mode
--
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

--
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8mb4';

--
-- Set default database
--
USE report;

--
-- Drop procedure `Proc_AllTable_Count`
--
DROP PROCEDURE IF EXISTS Proc_AllTable_Count;

--
-- Drop procedure `Proc_AllTable_Delete`
--
DROP PROCEDURE IF EXISTS Proc_AllTable_Delete;

--
-- Drop procedure `Proc_AllTable_DeleteList`
--
DROP PROCEDURE IF EXISTS Proc_AllTable_DeleteList;

--
-- Drop procedure `Proc_AllTable_GetAll`
--
DROP PROCEDURE IF EXISTS Proc_AllTable_GetAll;

--
-- Drop procedure `Proc_AllTable_GetAllByColumnName`
--
DROP PROCEDURE IF EXISTS Proc_AllTable_GetAllByColumnName;

--
-- Drop procedure `Proc_AllTable_GetByCode`
--
DROP PROCEDURE IF EXISTS Proc_AllTable_GetByCode;

--
-- Drop procedure `Proc_AllTable_GetById`
--
DROP PROCEDURE IF EXISTS Proc_AllTable_GetById;

--
-- Drop procedure `Proc_AllTable_GetListByColumnValues`
--
DROP PROCEDURE IF EXISTS Proc_AllTable_GetListByColumnValues;

--
-- Drop procedure `Proc_Report_Filter`
--
DROP PROCEDURE IF EXISTS Proc_Report_Filter;

--
-- Drop procedure `Proc_Report_Insert`
--
DROP PROCEDURE IF EXISTS Proc_Report_Insert;

--
-- Drop procedure `Proc_Report_Update`
--
DROP PROCEDURE IF EXISTS Proc_Report_Update;

--
-- Drop table `report`
--
DROP TABLE IF EXISTS report;

--
-- Set default database
--
USE report;

--
-- Create table `report`
--
CREATE TABLE report (
  ReportId char(36) NOT NULL,
  ProvinceId varchar(255) DEFAULT NULL,
  ProvinceName varchar(255) DEFAULT NULL,
  DistrictId varchar(255) DEFAULT NULL,
  DistrictName varchar(255) DEFAULT NULL,
  WardId varchar(255) DEFAULT NULL,
  WardName varchar(255) DEFAULT NULL,
  Address varchar(255) DEFAULT NULL,
  CropStageId char(36) DEFAULT NULL,
  CropStageName varchar(255) DEFAULT NULL,
  PestStageId char(36) DEFAULT NULL,
  PestStageName varchar(255) DEFAULT NULL,
  CropId char(36) DEFAULT NULL,
  CropName varchar(255) DEFAULT NULL,
  PestId char(36) DEFAULT NULL,
  PestName varchar(255) DEFAULT NULL,
  CreatedDate datetime DEFAULT NULL,
  CreatedBy varchar(255) DEFAULT NULL,
  ModifiedDate datetime DEFAULT NULL,
  ReportName varchar(255) DEFAULT NULL,
  ReportDate datetime DEFAULT NULL,
  ModifiedBy varchar(255) DEFAULT NULL,
  PRIMARY KEY (ReportId)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
ROW_FORMAT = DYNAMIC;

DELIMITER $$

--
-- Create procedure `Proc_Report_Update`
--
CREATE PROCEDURE Proc_Report_Update (IN v_ReportId char(36), IN v_ProvinceId varchar(255), IN v_ProvinceName varchar(255), IN v_DistrictId varchar(255), IN v_DistrictName varchar(255), IN v_WardId varchar(255), IN v_WardName varchar(255), IN v_Address varchar(255), IN v_CropStageId char(36), IN v_PestStageId char(36), IN v_ModifiedDate datetime, IN v_ModifiedBy varchar(255), IN v_ReportName varchar(255), IN v_ReportDate datetime, IN v_id char(36), IN v_CropStageName varchar(255), IN v_PestStageName varchar(255), IN v_PestId char(36), IN v_PestName varchar(255), IN v_CropId char(36), IN v_CropName varchar(255))
SQL SECURITY INVOKER
COMMENT 'Procedure cập nhật thông tin dự đoán.'
BEGIN
  UPDATE report r
  SET ReportId = v_ReportId,
      ProvinceId = v_ProvinceId,
      ProvinceName = v_ProvinceName,
      DistrictId = v_DistrictId,
      DistrictName = v_DistrictName,
      WardId = v_WardId,
      WardName = v_WardName,
      Address = v_Address,
      CropStageId = v_CropStageId,
      CropStageName = v_CropStageName,
      PestStageId = v_PestStageId,
      PestStageName = v_PestStageName,
      CropId = v_CropId,
      CropName = v_CropName,
      PestId = v_PestId,
      PestName = v_PestName,
      ModifiedDate = v_ModifiedDate,
      ReportName = v_ReportName,
      ReportDate = v_ReportDate,
      ModifiedBy = v_ModifiedBy
  WHERE ReportId = v_id;
END
$$

--
-- Create procedure `Proc_Report_Insert`
--
CREATE PROCEDURE Proc_Report_Insert (IN v_ReportId char(36), IN v_ProvinceId varchar(255), IN v_ProvinceName varchar(255), IN v_DistrictId varchar(255), IN v_DistrictName varchar(255), IN v_WardId varchar(255), IN v_WardName varchar(255), IN v_Address varchar(255), IN v_CropStageId char(36), IN v_PestStageId char(36), IN v_CreatedDate datetime, IN v_CreatedBy varchar(255), IN v_ReportName varchar(255), IN v_ReportDate datetime, IN v_CropStageName varchar(255), IN v_PestStageName varchar(255), IN v_PestId char(36), IN v_PestName varchar(255), IN v_CropId char(36), IN v_CropName varchar(255))
SQL SECURITY INVOKER
COMMENT 'Procedure thêm báo cáo.'
BEGIN
  INSERT INTO report (ReportId, ProvinceId, ProvinceName, DistrictId, DistrictName, WardId, WardName, Address, CropStageId, CropStageName, PestStageId, PestStageName, CropId, CropName, PestId, PestName, CreatedDate, CreatedBy, ReportName, ReportDate)
    VALUES (v_ReportId, v_ProvinceId, v_ProvinceName, v_DistrictId, v_DistrictName, v_WardId, v_WardName, v_Address, v_CropStageId, v_CropStageName, v_PestStageId, v_PestStageName, v_CropId, v_CropName, v_PestId, v_PestName, v_CreatedDate, v_CreatedBy, v_ReportName, v_ReportDate);
END
$$

--
-- Create procedure `Proc_Report_Filter`
--
CREATE PROCEDURE Proc_Report_Filter (IN v_ProvinceId varchar(255), IN v_DistrictId varchar(255), IN v_WardId varchar(255), IN v_PageSize int, IN v_PageNumber int, IN v_ReportName varchar(255), IN v_ReportStartDate datetime, IN v_ReportEndDate datetime)
SQL SECURITY INVOKER
COMMENT 'Procedure lọc thông tin báo cáo theo điều kiện và trả về tổng số lượng.'
BEGIN
  DECLARE startIndex int;
  SET startIndex = (v_PageNumber - 1) * v_PageSize;

  -- Truy vấn dữ liệu với phân trang
  SELECT
    *
  FROM report p
  WHERE (v_ProvinceId IS NULL
  OR v_ProvinceId = ''
  OR p.ProvinceId = v_ProvinceId)
  AND (v_DistrictId IS NULL
  OR v_DistrictId = ''
  OR p.DistrictId = v_DistrictId)
  AND (v_WardId IS NULL
  OR v_WardId = ''
  OR p.WardId = v_WardId)
  AND (v_ReportName IS NULL
  OR v_ReportName = ''
  OR p.ReportName LIKE v_ReportName)
  AND (v_ReportStartDate IS NULL
  OR v_ReportEndDate IS NULL
  OR (p.ReportDate >= v_ReportStartDate
  && p.ReportDate <= v_ReportEndDate))
  LIMIT startIndex, v_PageSize;

  -- Truy vấn tổng số lượng bản ghi
  SELECT
    COUNT(*) AS Total
  FROM report p
  WHERE (v_ProvinceId IS NULL
  OR v_ProvinceId = ''
  OR p.ProvinceId = v_ProvinceId)
  AND (v_DistrictId IS NULL
  OR v_DistrictId = ''
  OR p.DistrictId = v_DistrictId)
  AND (v_WardId IS NULL
  OR v_WardId = ''
  OR p.WardId = v_WardId)
  AND (v_ReportName IS NULL
  OR v_ReportName = ''
  OR p.ReportName LIKE v_ReportName)
  AND (v_ReportStartDate IS NULL
  OR v_ReportEndDate IS NULL
  OR (p.ReportDate >= v_ReportStartDate
  && p.ReportDate <= v_ReportEndDate))
  ;
END
$$

--
-- Create procedure `Proc_AllTable_GetListByColumnValues`
--
CREATE PROCEDURE Proc_AllTable_GetListByColumnValues (IN `tableName` varchar(255), IN `columnName` varchar(255), IN `values` text)
SQL SECURITY INVOKER
COMMENT 'Procedure lấy ra danh sách bản ghi theo một chuỗi các giá trị của một trường.'
BEGIN
  SET @query = CONCAT('SELECT * FROM ', tableName, ' entity WHERE entity.', columnName, ' IN (', `values`, ')');
  PREPARE stmt FROM @query;
  EXECUTE stmt;

  /* giải phóng tài nguyên */
  DEALLOCATE PREPARE stmt;
END
$$

--
-- Create procedure `Proc_AllTable_GetById`
--
CREATE PROCEDURE Proc_AllTable_GetById (IN `tableName` varchar(255), IN `tableId` varchar(255), IN `id` char(36))
SQL SECURITY INVOKER
COMMENT 'Procedure lấy một bản ghi theo id.'
BEGIN
  SET @query = CONCAT('SELECT * FROM ', tableName, ' entity WHERE entity.', tableId, ' = \'', id, '\'');
  PREPARE stmt FROM @query;
  EXECUTE stmt;

  /* giải phóng tài nguyên */
  DEALLOCATE PREPARE stmt;
END
$$

--
-- Create procedure `Proc_AllTable_GetByCode`
--
CREATE PROCEDURE Proc_AllTable_GetByCode (IN `tableName` varchar(255), IN `tableCode` varchar(255), IN `code` varchar(20))
SQL SECURITY INVOKER
COMMENT 'Procedure lấy bản ghi theo mã code.'
BEGIN
  SET @query = CONCAT('SELECT * FROM ', tableName, ' entity WHERE entity.', tableCode, ' = \'', code, '\'');
  PREPARE stmt FROM @query;
  EXECUTE stmt;

  /* giải phóng tài nguyên */
  DEALLOCATE PREPARE stmt;
END
$$

--
-- Create procedure `Proc_AllTable_GetAllByColumnName`
--
CREATE PROCEDURE Proc_AllTable_GetAllByColumnName (IN `tableName` varchar(255), IN `columnName` varchar(255))
SQL SECURITY INVOKER
COMMENT 'Procedure lấy tất cả bản ghi của một bảng nhưng chỉ lấy một cột.'
BEGIN
  SET @query = CONCAT('SELECT ', columnName, ' FROM ', tableName);
  PREPARE stmt FROM @query;
  EXECUTE stmt;

  /* giải phóng tài nguyên */
  DEALLOCATE PREPARE stmt;
END
$$

--
-- Create procedure `Proc_AllTable_GetAll`
--
CREATE PROCEDURE Proc_AllTable_GetAll (IN `tableName` varchar(255))
SQL SECURITY INVOKER
COMMENT 'Procedure lấy tất cả bản ghi trong 1 bảng.'
BEGIN
  SET @query = CONCAT('SELECT * FROM ', tableName);
  PREPARE stmt FROM @query;
  EXECUTE stmt;

  /* giải phóng tài nguyên */
  DEALLOCATE PREPARE stmt;
END
$$

--
-- Create procedure `Proc_AllTable_DeleteList`
--
CREATE PROCEDURE Proc_AllTable_DeleteList (IN `tableName` varchar(255), IN `tableId` varchar(255), IN `ids` text)
SQL SECURITY INVOKER
COMMENT 'Procedure xóa nhiều bản ghi theo id.'
BEGIN
  SET @query = CONCAT('DELETE FROM ', tableName, ' WHERE ', tableId, ' IN (', ids, ')');
  PREPARE stmt FROM @query;
  EXECUTE stmt;

  /* giải phóng tài nguyên */
  DEALLOCATE PREPARE stmt;
END
$$

--
-- Create procedure `Proc_AllTable_Delete`
--
CREATE PROCEDURE Proc_AllTable_Delete (IN `tableName` varchar(255), IN `tableId` varchar(255), IN `id` char(36))
SQL SECURITY INVOKER
COMMENT 'Procedure xóa 1 bản ghi.'
BEGIN
  SET @query = CONCAT('DELETE FROM ', tableName, ' WHERE ', tableId, ' = \'', id, '\'');
  PREPARE stmt FROM @query;
  EXECUTE stmt;

  /* giải phóng tài nguyên */
  DEALLOCATE PREPARE stmt;
END
$$

--
-- Create procedure `Proc_AllTable_Count`
--
CREATE PROCEDURE Proc_AllTable_Count (IN `tableName` varchar(255))
SQL SECURITY INVOKER
COMMENT 'Procedure để đếm số bản ghi trong 1 bảng.'
BEGIN
  SET @query = CONCAT('SELECT COUNT(1) FROM ', tableName);
  PREPARE stmt FROM @query;
  EXECUTE stmt;

  /* giải phóng tài nguyên */
  DEALLOCATE PREPARE stmt;
END
$$

DELIMITER ;

-- Table report.report does not contain any data (it is empty)

--
-- Restore previous SQL mode
--
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;