name: Trigger Jenkins Build Test

on:
  push:
    branches: [ "test", "release" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: git fetch --prune --unshallow
      
    - name: Get the current branch
      id: get_branch
      run: |
        echo "Branch: ${GITHUB_REF#refs/heads/}"
        echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

    - name: Check for changes in FE folder
      id: check_fe
      run: |
        git diff --name-only HEAD^ HEAD | grep '^FE/' || echo "No changes in FE folder"
      continue-on-error: true

    - name: Check for changes in BE folder
      id: check_be
      run: |
        git diff --name-only HEAD^ HEAD | grep '^BE/' || echo "No changes in BE folder"
      continue-on-error: true

    - name: Trigger Jenkins job for FE
      if: steps.check_fe.outputs.stdout != 'No changes in FE folder'
      run: |
        curl -X POST "http://68.183.191.110:8080/job/PEMS_FE/buildWithParameters" \
          -H "Content-Type: application/x-www-form-urlencoded" \
          -d "ENV_BUILD=$BRANCH_NAME&IMAGE_TAG=r1.0.1" \
          -u ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}

    - name: Trigger Jenkins job for BE
      if: steps.check_be.outputs.stdout != 'No changes in BE folder'
      run: |
        curl -X POST "http://68.183.191.110:8080/job/PEMS_BE/buildWithParameters" \
          -H "Content-Type: application/x-www-form-urlencoded" \
          -d "ENV_BUILD=$BRANCH_NAME&IMAGE_TAG=r1.0.1" \
          -u ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}
